---
abstract: 'Control a hypnocube http://www.hypnocube.com/'
author:
  - 'Kevin Mulholland <moodfarm@cpan.org>'
build_requires:
  File::Basename: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Device-Hypnocube
requires:
  App::Basis: '0'
  Dancer: '0'
  Data::Hexdumper: '0'
  Data::Printer: '0'
  Digest::CRC: '0'
  Fcntl: '0'
  Moo: '0'
  Path::Tiny: '0'
  Time::HiRes: '0'
  Try::Tiny: '0'
  WebColors: '0'
  YAML::XS: '0'
  constant: '0'
  perl: v5.16.0
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  repository: git://github.com/27escape/Device-Hypnocube.git
version: '1.8'
